package com.melky.bot.vk;

public enum VKBotState {
    SHOW_MAIN_MENU,
    START,
    CHANGE_CITY,
    SHOW_CURRENT_WEATHER,
    SHOW_TODO_LIST,
    EDIT_LIST,
    EDIT_CURRENT_ELEMENT,
    EDIT_TEXT_ELEMENT,
    EDIT_IS_SUCCESS_ELEMENT,
    SAVE_TEXT_ELEMENT,
    UNKNOWN_MESSAGE,
    CREATE_TODO_LIST;

}
